apiVersion: apps/v1
kind: Deployment
metadata:
  name: maven-app
  namespace: default
  labels:
    app: maven-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maven-app
  template:
    metadata:
      labels:
        app: maven-app
    spec:
      containers:
      - name: maven-app
        image: "us-central1-docker.pkg.dev/gcp-jenkins-terraform/maven-app:v9"
---
# spec:
#   scaleTargetRef:
#     kind: Deployment
#     name: maven-app
#     apiVersion: apps/v1
#   minReplicas: 1
#   metrics:
#   - type: Resource
#     resource:
#       name: "cpu"
#       target:
#         type: "Utilization"
#         averageUtilization: 80
#---
apiVersion: v1
kind: Service
metadata:
  name: maven-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: maven-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080